<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="11" hostname="MAMATHA" failures="1" tests="1" name="Default test" time="13.29" errors="0" timestamp="2023-04-20T03:47:29 IST">
  <testcase classname="com.CambriaProject.qa.testcases.LoginTest" name="Seeting_Page_Postload_Data" time="1.888">
    <failure type="java.lang.AssertionError" message="expected [] but found [123456789]">
      <![CDATA[java.lang.AssertionError: expected [] but found [123456789]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.CambriaProject.qa.testcases.LoginTest.Seeting_Page_Postload_Data(LoginTest.java:184)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Seeting_Page_Postload_Data -->
  <testcase classname="com.CambriaProject.qa.testcases.LoginTest" name="Login_With_INValid_Password_Different_User" time="0.0">
    <ignored/>
  </testcase> <!-- Login_With_INValid_Password_Different_User -->
  <testcase classname="com.CambriaProject.qa.testcases.LoginTest" name="Login_with_emptyData_Password" time="0.0">
    <ignored/>
  </testcase> <!-- Login_with_emptyData_Password -->
  <testcase classname="com.CambriaProject.qa.testcases.LoginTest" name="Login_with_Valid_Password_Invalid_Email_ID" time="0.0">
    <ignored/>
  </testcase> <!-- Login_with_Valid_Password_Invalid_Email_ID -->
  <testcase classname="com.CambriaProject.qa.testcases.LoginTest" name="Login_With_Valid_Email_ID" time="0.0">
    <ignored/>
  </testcase> <!-- Login_With_Valid_Email_ID -->
  <testcase classname="com.CambriaProject.qa.testcases.LoginTest" name="LogOut_Functionality" time="0.0">
    <ignored/>
  </testcase> <!-- LogOut_Functionality -->
  <testcase classname="com.CambriaProject.qa.testcases.LoginTest" name="Login_With_Invalid_Character__Email_ID_Data" time="0.0">
    <ignored/>
  </testcase> <!-- Login_With_Invalid_Character__Email_ID_Data -->
  <testcase classname="com.CambriaProject.qa.testcases.LoginTest" name="Seeting_button_Functionality" time="0.0">
    <ignored/>
  </testcase> <!-- Seeting_button_Functionality -->
  <testcase classname="com.CambriaProject.qa.testcases.LoginTest" name="Login_without_Email_ID" time="0.0">
    <ignored/>
  </testcase> <!-- Login_without_Email_ID -->
  <testcase classname="com.CambriaProject.qa.testcases.LoginTest" name="Seeting_Page_Preload_Data" time="0.0">
    <ignored/>
  </testcase> <!-- Seeting_Page_Preload_Data -->
  <testcase classname="com.CambriaProject.qa.testcases.LoginTest" name="Login_with_Email_ID_without_domain_name_or_without_com_Extention" time="0.0">
    <ignored/>
  </testcase> <!-- Login_with_Email_ID_without_domain_name_or_without_com_Extention -->
  <testcase classname="com.CambriaProject.qa.testcases.LoginTest" name="Login_With_Invalid_Password_Data" time="0.0">
    <ignored/>
  </testcase> <!-- Login_With_Invalid_Password_Data -->
</testsuite> <!-- Default test -->
